# Generated by Django 3.1.1 on 2020-09-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Avatar",
        ),
    ]
