# Generated by Django 3.1.1 on 2020-09-21 16:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatarimage",
            name="image",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="default.jpg", upload_to=core.models.user_image_file_path
            ),
        ),
    ]
